/* This file is generated by zits. Do not edit manually */

export enum OutputUnitEnum {
	SvgMarker = 'SvgMarker',
	EmojiGroup = 'EmojiGroup',
	Template = 'Template',
	Space = 'Space',
}

export enum OutputLinkType {
	Topics = 'Topics',
	Threads = 'Threads',
	Favorite = 'Favorite',
	Dm = 'Dm',
}
export enum OutputUnitEnum {
	SemanticTopic = 'SemanticTopic',
	ParticipationProtocol = 'ParticipationProtocol',
}

export enum OutputLinkType {
}
export enum OutputUnitEnum {
}

export enum OutputLinkType {
	Default = 'Default',
	ToValues = 'ToValues',
}
