/* This file is generated by zits. Do not edit manually */

import {Animal, AnimalTwo, DirectMessageProtocol, ExternalMessage, FakeMessage, Foo, MarkerPiece, MembraneThreshold, Message, PlaysetEntry, SystemSignalProtocol, } from './output.types';
import {ZomeProxy} from '@ddd-qc/lit-happ';
import {outputFunctionNames} from './output.fn';

/**
 *
 */
export class OutputProxy extends ZomeProxy {
  static readonly DEFAULT_ZOME_NAME = "output"
  static readonly FN_NAMES = outputFunctionNames
 }
