/* This file is generated by zits. Do not edit manually */

import {Message, ExternalMessage, Animal, AnimalTwo, Foo, MarkerPiece, PlaysetEntry, Message, FakeMessage, MembraneThreshold, DirectMessageProtocol, } from './output.types';
import {ZomeProxy} from '@ddd-qc/lit-happ';
import {outputFunctionNames} from './output.fn';

/**
 *
 */
export class OutputProxy extends ZomeProxy {
  static readonly DEFAULT_ZOME_NAME = "output"
  static readonly FN_NAMES = outputFunctionNames
 }
