/* This file is generated by zits. Do not edit manually */

// @ts-ignore
import {TaggingEntry, TaggingLinkTypes, } from './output.types';
import {ZomeProxy} from '@ddd-qc/lit-happ';
import {outputFunctionNames} from './output.fn';



/**
 *
 */
export class OutputProxy extends ZomeProxy {
  static override readonly DEFAULT_ZOME_NAME = "output";
  static override readonly FN_NAMES = outputFunctionNames;
  static override readonly ENTRY_TYPES = [];
  static override readonly LINK_TYPES = [];
 
  async getAllPlaysets(): Promise<HcRecord[]> {
    return this.call('get_all_playsets', null);
  }
}
