/* This file is generated by zits. Do not edit manually */

import {} from './output.types';
import {ZomeProxy} from '@ddd-qc/lit-happ';
import {outputFunctionNames} from './output.fn';

/**
 *
 */
export class OutputProxy extends ZomeProxy {
  static readonly DEFAULT_ZOME_NAME = "output"
  static readonly FN_NAMES = outputFunctionNames
 
  async exportPiece(input: ExportPieceInput): Promise<void> {
    return this.call('export_piece', input);
  }

  async getSessionFromEh(sessionEh: EntryHashB64): Promise<PlacementSession | null> {
    return this.call('get_session_from_eh', sessionEh);
  }

  async createNextSession(input: CreateNextSessionInput): Promise<[EntryHashB64, number]> {
    return this.call('create_next_session', input);
  }

  async getAllPlaysets(): Promise<PlaysetOutput[]> {
    return this.call('get_all_playsets', null);
  }

  async exportPlayset(input: ExportPlaysetInput): Promise<EntryHashB64[]> {
    return this.call('export_playset', input);
  }

}
