/* This file is generated by zits. Do not edit manually */

import {ZomeName, FunctionName} from '@holochain/client';


/** Array of all zome function names in "output" */
export const outputFunctionNames: FunctionName[] = [
	"entry_defs",
	"export_piece",
	"get_session_from_eh",
	"create_next_session",
	"get_all_playsets",
	"export_playset",
];


/** Generate tuple array of function names with given zomeName */
export function generateOutputZomeFunctionsArray(zomeName: ZomeName): [ZomeName, FunctionName][] {
   let fns: [ZomeName, FunctionName][] = [];
   for (const fn of outputFunctionNames) {
      fns.push([zomeName, fn]);
   }
   return fns;
}


/** Tuple array of all zome function names with default zome name "output" */
export const outputZomeFunctions: [ZomeName, FunctionName][] = generateOutputZomeFunctionsArray("output");
