/* This file is generated by zits. Do not edit manually */

import {ZomeName, FunctionName} from '@holochain/client';

/** Array of all zome function names in "test" */
export const testFunctionNames: FunctionName[] = [
	"entry_defs",
	"export_piece",
	"get_session_from_eh",
	"create_next_session",
	"get_all_playsets",
	"export_playset",
];


/** Generate tuple array of function names with given zomeName */
export function generateTestZomeFunctionsArray(zomeName: ZomeName): [ZomeName, FunctionName][] {
   let fns: [ZomeName, FunctionName][] = [];
   for (const fn of testFunctionNames) {
      fns.push([zomeName, fn]);
   }
   return fns;
}


/** Tuple array of all zome function names with default zome name "test" */
export const testZomeFunctions: [ZomeName, FunctionName][] = generateTestZomeFunctionsArray("test");
